# Generated by Django 4.0.1 on 2022-01-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_partition'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='partition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.partition'),
        ),
    ]
