# Generated by Django 4.0.1 on 2022-01-27 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_region_post_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='region',
        ),
    ]
