# Generated by Django 4.0.1 on 2022-02-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_description_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
