# Generated by Django 4.0.1 on 2022-02-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='region',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='img/default.jpg', upload_to='media/img/'),
        ),
    ]
