# Generated by Django 4.0.1 on 2022-02-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_partition_url_region_url_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
        migrations.AlterField(
            model_name='region',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
    ]
