# Generated by Django 4.0.1 on 2022-02-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_partition_url_alter_region_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partition',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='region',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
